"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowUp,ArrowRight,RefreshCw,Search,ShieldCheck,Sparkles} from "lucide-react";
import {get,post,AppRecord,ChatResponse,ResearchRun} from "../lib/api";
import ResearchView from "../components/ResearchView";

type Entry={question:string;response:ChatResponse};
const suggestions=["Tell me about Salesforce","How does Slack authentication work?","How do I get HubSpot credentials?","Does Stripe have an API?"];
export default function Home(){
  const [message,setMessage]=useState("");const [session,setSession]=useState("");const [entries,setEntries]=useState<Entry[]>([]);const [active,setActive]=useState<AppRecord|null>(null);const [run,setRun]=useState<ResearchRun|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const bottom=useRef<HTMLDivElement>(null);
  useEffect(()=>{const id=localStorage.getItem("fieldnote-session");if(id)setSession(id);const requested=new URLSearchParams(location.search).get("app");if(requested){get<AppRecord>(`/api/apps/${requested}`).then(a=>send(`Research ${a.name}`,a.id)).catch(()=>{});}},[]);
  useEffect(()=>{if(!run||!["queued","running"].includes(run.status))return;const timer=setInterval(()=>get<ResearchRun>(`/api/runs/${run.id}`).then(setRun).catch(()=>{}),1500);return()=>clearInterval(timer)},[run?.id,run?.status]);
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[entries.length,run?.status]);
  async function send(value=message,appId?:number,refresh=false){if(!value.trim()&&!appId)return;setBusy(true);setError("");setMessage("");try{const response=await post<ChatResponse>("/api/chat",{message:value,session_id:session||undefined,app_id:appId,refresh});setSession(response.session_id);localStorage.setItem("fieldnote-session",response.session_id);setEntries(e=>[...e,{question:value,response}]);if(response.app){setActive(response.app);setRun(response.run||null)}}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}
  return <div className="chat-page"><header className="topbar"><div><span className="topbar-kicker">RESEARCH WORKSPACE</span><h1>Integration Researcher</h1></div><div className="context-indicator"><span className={`context-light ${active?"on":""}`}/>{active?active.name:"No active application"}</div></header>
    <div className="chat-scroll"><div className="chat-width">{entries.length===0?<div className="welcome"><div className="welcome-icon"><Search size={26}/></div><span className="eyebrow">A FOCUSED RESEARCH ASSISTANT</span><h2>Know the integration<br/><em>before you build it.</em></h2><p>Research the 100 applications in your dataset. Ask about authentication, credentials, APIs, MCP support, and feasibility. Every finding points back to evidence.</p><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>send(s)}>{s}<ArrowRight size={15}/></button>)}</div><div className="welcome-foot"><ShieldCheck size={15}/> Scope locked to the supplied 100 applications</div></div>:<div className="conversation">{entries.map((entry,i)=><div className="exchange" key={i}><div className="user-message"><span>You</span><p>{entry.question}</p></div><div className="assistant-message"><div className="assistant-avatar"><Sparkles size={16}/></div><div className="assistant-content">{entry.response.app&&i===entries.length-1?<><div className="answer-topline">FIELDNOTE ANALYSIS <span>· {entry.response.app.category}</span></div>{entry.response.type==="config_required"&&<div className="notice"><strong>Live research is not configured</strong><p>{entry.response.message}</p></div>}<ResearchView app={entry.response.app} run={run} focus={entry.response.focus}/>{run?.status==="completed"&&<button className="refresh-btn" onClick={()=>send(`Refresh research for ${entry.response.app?.name}`,entry.response.app?.id,true)}><RefreshCw size={14}/> Refresh research</button>}</>:<div className="plain-answer">{entry.response.message}</div>}</div></div></div>)}<div ref={bottom}/></div>}</div></div>
    <div className="composer-area"><form className="composer" onSubmit={e=>{e.preventDefault();send()}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder={active?`Ask about ${active.name}…`:"Ask about an application…"} aria-label="Ask a research question"/><button type="submit" disabled={busy||!message.trim()} aria-label="Send"><ArrowUp size={18}/></button></form>{error&&<p className="composer-error">{error}</p>}<p className="composer-hint">Research is limited to the assignment dataset. Source quality and access may vary.</p></div>
  </div>;
}
