import {ArrowDown,ExternalLink} from "lucide-react";
const steps=[
  ["01","Dataset resolver","Only one of the 100 named applications can enter the pipeline."],
  ["02","Tavily Search","Four targeted queries discover current documentation and access pages."],
  ["03","Tavily Extract","Page text is retrieved with source URL and timestamp."],
  ["04","Parallel specialists","Gemini 2.5 Flash examines auth, credential access, API surface, and MCP separately through LangGraph."],
  ["05","Evidence verification","Exact quote presence is checked; Gemini judges whether it supports each claim."],
  ["06","Research database","Sources, initial claims, verifier outcomes, runs and human review records are stored."],
];
export default function Methodology(){return <div className="page-pad"><div className="page-heading"><div><span className="eyebrow">HOW THE RESEARCH WORKS</span><h1>Methodology</h1><p>A bounded, repeatable route from an application name to sourced findings.</p></div></div><div className="method-layout"><div className="flow">{steps.map(([num,title,desc],i)=><div key={num}><div className="flow-step"><span>{num}</span><div><h2>{title}</h2><p>{desc}</p></div></div>{i<steps.length-1&&<ArrowDown className="flow-arrow" size={17}/>}</div>)}</div><aside className="method-aside"><div className="panel"><span className="eyebrow">BOUNDARIES</span><h2>Evidence rules</h2><p>The assignment hint seeds discovery; it is never treated as proof. Unverifiable statements stay out of the final dossier. Lack of an MCP search result is recorded as unknown, never as a claim of absence.</p></div><div className="panel"><span className="eyebrow">HUMAN WORK</span><h2>Sample audit</h2><p>A reviewer must open original documentation for sampled apps, compare key claims, and record correct, incorrect or uncertain judgments. Accuracy statistics require those review records.</p></div><div className="panel"><span className="eyebrow">FRESHNESS</span><h2>Reuse and refresh</h2><p>Completed research is cached for seven days by default. Refresh starts a new run while retaining earlier evidence and outcomes for audit.</p></div><a className="method-link" href="https://docs.tavily.com/documentation/api-reference/introduction" target="_blank" rel="noreferrer">Tavily API documentation <ExternalLink size={14}/></a></aside></div></div>}
